#pragma once

// Defaults shared by audio-board presets and custom audio hardware. Display,
// buttons, LEDs, storage, and cameras intentionally do not belong here.

#ifndef XIAOZHI_AUDIO_PROFILE
#define XIAOZHI_AUDIO_PROFILE XIAOZHI_AUDIO_PROFILE_ES8311
#endif
#ifndef XIAOZHI_AUDIO_ENABLE_WAKE_ESP_SR
#define XIAOZHI_AUDIO_ENABLE_WAKE_ESP_SR 0
#endif

#ifndef BOARD_AUDIO_I2C_SDA
#define BOARD_AUDIO_I2C_SDA -1
#endif
#ifndef BOARD_AUDIO_I2C_SCL
#define BOARD_AUDIO_I2C_SCL -1
#endif
#ifndef BOARD_AUDIO_I2C_FREQUENCY
#define BOARD_AUDIO_I2C_FREQUENCY 400000
#endif
#ifndef BOARD_AUDIO_CODEC_ADDRESS
#define BOARD_AUDIO_CODEC_ADDRESS 0x18
#endif

#ifndef BOARD_AUDIO_OUTPUT_I2S_PORT
#if XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_PDM_I2S
#define BOARD_AUDIO_OUTPUT_I2S_PORT 1
#else
#define BOARD_AUDIO_OUTPUT_I2S_PORT 0
#endif
#endif
#ifndef BOARD_AUDIO_OUTPUT_SAMPLE_RATE
#define BOARD_AUDIO_OUTPUT_SAMPLE_RATE 24000
#endif
#ifndef BOARD_AUDIO_OUTPUT_MCLK
#define BOARD_AUDIO_OUTPUT_MCLK -1
#endif
#ifndef BOARD_AUDIO_OUTPUT_BCLK
#define BOARD_AUDIO_OUTPUT_BCLK -1
#endif
#ifndef BOARD_AUDIO_OUTPUT_WS
#define BOARD_AUDIO_OUTPUT_WS -1
#endif
#ifndef BOARD_AUDIO_OUTPUT_DATA
#define BOARD_AUDIO_OUTPUT_DATA -1
#endif
#ifndef BOARD_AUDIO_OUTPUT_MCLK_INVERTED
#define BOARD_AUDIO_OUTPUT_MCLK_INVERTED false
#endif
#ifndef BOARD_AUDIO_OUTPUT_BCLK_INVERTED
#define BOARD_AUDIO_OUTPUT_BCLK_INVERTED false
#endif
#ifndef BOARD_AUDIO_OUTPUT_WS_INVERTED
#define BOARD_AUDIO_OUTPUT_WS_INVERTED false
#endif
#ifndef BOARD_AUDIO_OUTPUT_DATA_BITS
#if XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_ES8311 || \
    XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_CUSTOM_CODEC
#define BOARD_AUDIO_OUTPUT_DATA_BITS 16
#else
#define BOARD_AUDIO_OUTPUT_DATA_BITS 32
#endif
#endif
#ifndef BOARD_AUDIO_OUTPUT_VALID_BITS
#define BOARD_AUDIO_OUTPUT_VALID_BITS 16
#endif
#ifndef BOARD_AUDIO_OUTPUT_SLOT_BITS
#if BOARD_AUDIO_OUTPUT_DATA_BITS == 16
#define BOARD_AUDIO_OUTPUT_SLOT_BITS 16
#else
#define BOARD_AUDIO_OUTPUT_SLOT_BITS 32
#endif
#endif
#ifndef BOARD_AUDIO_OUTPUT_CHANNELS
#if XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_ES8311 || \
    XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_CUSTOM_CODEC
#define BOARD_AUDIO_OUTPUT_CHANNELS 2
#else
#define BOARD_AUDIO_OUTPUT_CHANNELS 1
#endif
#endif
#ifndef BOARD_AUDIO_OUTPUT_SLOT
#if BOARD_AUDIO_OUTPUT_CHANNELS == 2
#define BOARD_AUDIO_OUTPUT_SLOT I2sOpusAudioPort::I2sSlot::Both
#else
#define BOARD_AUDIO_OUTPUT_SLOT I2sOpusAudioPort::I2sSlot::Left
#endif
#endif

#ifndef BOARD_AUDIO_INPUT_I2S_PORT
#if XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_I2S_SIMPLEX
#define BOARD_AUDIO_INPUT_I2S_PORT 1
#else
#define BOARD_AUDIO_INPUT_I2S_PORT 0
#endif
#endif
#ifndef BOARD_AUDIO_INPUT_SAMPLE_RATE
#if XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_I2S_SIMPLEX
#define BOARD_AUDIO_INPUT_SAMPLE_RATE 16000
#else
#define BOARD_AUDIO_INPUT_SAMPLE_RATE 24000
#endif
#endif
#ifndef BOARD_AUDIO_INPUT_MCLK
#define BOARD_AUDIO_INPUT_MCLK -1
#endif
#ifndef BOARD_AUDIO_INPUT_BCLK
#define BOARD_AUDIO_INPUT_BCLK -1
#endif
#ifndef BOARD_AUDIO_INPUT_WS
#define BOARD_AUDIO_INPUT_WS -1
#endif
#ifndef BOARD_AUDIO_INPUT_DATA
#define BOARD_AUDIO_INPUT_DATA -1
#endif
#ifndef BOARD_AUDIO_INPUT_MCLK_INVERTED
#define BOARD_AUDIO_INPUT_MCLK_INVERTED false
#endif
#ifndef BOARD_AUDIO_INPUT_BCLK_INVERTED
#define BOARD_AUDIO_INPUT_BCLK_INVERTED false
#endif
#ifndef BOARD_AUDIO_INPUT_WS_INVERTED
#define BOARD_AUDIO_INPUT_WS_INVERTED false
#endif
#ifndef BOARD_AUDIO_INPUT_DATA_BITS
#if XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_ES8311 || \
    XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_CUSTOM_CODEC
#define BOARD_AUDIO_INPUT_DATA_BITS 16
#else
#define BOARD_AUDIO_INPUT_DATA_BITS 32
#endif
#endif
#ifndef BOARD_AUDIO_INPUT_VALID_BITS
#if BOARD_AUDIO_INPUT_DATA_BITS == 16
#define BOARD_AUDIO_INPUT_VALID_BITS 16
#else
#define BOARD_AUDIO_INPUT_VALID_BITS 24
#endif
#endif
#ifndef BOARD_AUDIO_INPUT_SLOT_BITS
#if BOARD_AUDIO_INPUT_DATA_BITS == 16
#define BOARD_AUDIO_INPUT_SLOT_BITS 16
#else
#define BOARD_AUDIO_INPUT_SLOT_BITS 32
#endif
#endif
#ifndef BOARD_AUDIO_INPUT_CHANNELS
#if XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_ES8311 || \
    XIAOZHI_AUDIO_PROFILE == XIAOZHI_AUDIO_PROFILE_CUSTOM_CODEC
#define BOARD_AUDIO_INPUT_CHANNELS 2
#else
#define BOARD_AUDIO_INPUT_CHANNELS 1
#endif
#endif
#ifndef BOARD_AUDIO_INPUT_SLOT
#if BOARD_AUDIO_INPUT_CHANNELS == 2
#define BOARD_AUDIO_INPUT_SLOT I2sOpusAudioPort::I2sSlot::Both
#else
#define BOARD_AUDIO_INPUT_SLOT I2sOpusAudioPort::I2sSlot::Left
#endif
#endif
#ifndef BOARD_AUDIO_INPUT_RIGHT_SHIFT
#if BOARD_AUDIO_INPUT_DATA_BITS == 16
#define BOARD_AUDIO_INPUT_RIGHT_SHIFT 0
#else
#define BOARD_AUDIO_INPUT_RIGHT_SHIFT 12
#endif
#endif
#ifndef BOARD_AUDIO_CAPTURE_CHANNEL
#define BOARD_AUDIO_CAPTURE_CHANNEL I2sOpusAudioPort::CaptureChannel::Left
#endif

#ifndef BOARD_AUDIO_PDM_I2S_PORT
#define BOARD_AUDIO_PDM_I2S_PORT 0
#endif
#ifndef BOARD_AUDIO_PDM_SAMPLE_RATE
#define BOARD_AUDIO_PDM_SAMPLE_RATE 16000
#endif
#ifndef BOARD_AUDIO_PDM_CLOCK
#define BOARD_AUDIO_PDM_CLOCK -1
#endif
#ifndef BOARD_AUDIO_PDM_DATA
#define BOARD_AUDIO_PDM_DATA -1
#endif
#ifndef BOARD_AUDIO_PDM_CLOCK_INVERTED
#define BOARD_AUDIO_PDM_CLOCK_INVERTED false
#endif

#ifndef BOARD_AUDIO_AMP_ENABLE_PIN
#define BOARD_AUDIO_AMP_ENABLE_PIN -1
#endif
#ifndef BOARD_AUDIO_AMP_ACTIVE_LEVEL
#define BOARD_AUDIO_AMP_ACTIVE_LEVEL true
#endif
#ifndef BOARD_AUDIO_AMP_VOLUME_PERCENT
#define BOARD_AUDIO_AMP_VOLUME_PERCENT 70
#endif

#ifndef BOARD_AUDIO_CODEC_INITIALIZE_WIRE
#define BOARD_AUDIO_CODEC_INITIALIZE_WIRE true
#endif
#ifndef BOARD_AUDIO_CODEC_RESET_ON_BEGIN
#define BOARD_AUDIO_CODEC_RESET_ON_BEGIN true
#endif
#ifndef BOARD_AUDIO_CODEC_RESET_DELAY_MS
#define BOARD_AUDIO_CODEC_RESET_DELAY_MS 10
#endif
#ifndef BOARD_AUDIO_CODEC_PA_PIN
#define BOARD_AUDIO_CODEC_PA_PIN -1
#endif
#ifndef BOARD_AUDIO_CODEC_PA_ACTIVE_LEVEL
#define BOARD_AUDIO_CODEC_PA_ACTIVE_LEVEL true
#endif
#ifndef BOARD_AUDIO_CODEC_USE_MCLK
#define BOARD_AUDIO_CODEC_USE_MCLK true
#endif
#ifndef BOARD_AUDIO_CODEC_MASTER
#define BOARD_AUDIO_CODEC_MASTER false
#endif
#ifndef BOARD_AUDIO_CODEC_NO_DAC_REFERENCE
#define BOARD_AUDIO_CODEC_NO_DAC_REFERENCE true
#endif
#ifndef BOARD_AUDIO_MCLK_MULTIPLE
#define BOARD_AUDIO_MCLK_MULTIPLE 256
#endif
#ifndef BOARD_AUDIO_PA_SUPPLY_VOLTAGE
#define BOARD_AUDIO_PA_SUPPLY_VOLTAGE 5.0f
#endif
#ifndef BOARD_AUDIO_CODEC_DAC_VOLTAGE
#define BOARD_AUDIO_CODEC_DAC_VOLTAGE 3.3f
#endif
#ifndef BOARD_AUDIO_PA_GAIN_DB
#define BOARD_AUDIO_PA_GAIN_DB 0.0f
#endif
#ifndef BOARD_AUDIO_MIC_GAIN_DB
#define BOARD_AUDIO_MIC_GAIN_DB 36.0f
#endif
#ifndef BOARD_AUDIO_OUTPUT_VOLUME_DB
#define BOARD_AUDIO_OUTPUT_VOLUME_DB -12.0f
#endif
