#pragma once

// OpenJumper ESP32 AIOT Basic / oj_esp32s3basic.
// Source: aily-blockly-boards/oj_esp32s3basic/board.json, version 1.0.1.

#define XIAOZHI_AUDIO_PROFILE XIAOZHI_AUDIO_PROFILE_ES8311
#define XIAOZHI_AUDIO_ENABLE_WAKE_ESP_SR 1

// ES8311 control and shared full-duplex I2S.
#define BOARD_AUDIO_I2C_SDA 41
#define BOARD_AUDIO_I2C_SCL 42
#define BOARD_AUDIO_I2C_FREQUENCY 400000
#define BOARD_AUDIO_CODEC_ADDRESS 0x18

#define BOARD_AUDIO_OUTPUT_I2S_PORT 0
#define BOARD_AUDIO_OUTPUT_SAMPLE_RATE 24000
#define BOARD_AUDIO_OUTPUT_MCLK 46
#define BOARD_AUDIO_OUTPUT_BCLK 39
#define BOARD_AUDIO_OUTPUT_WS 2
#define BOARD_AUDIO_OUTPUT_DATA 38
#define BOARD_AUDIO_OUTPUT_DATA_BITS 16
#define BOARD_AUDIO_OUTPUT_VALID_BITS 16
#define BOARD_AUDIO_OUTPUT_SLOT_BITS 16
#define BOARD_AUDIO_OUTPUT_CHANNELS 2
#define BOARD_AUDIO_OUTPUT_SLOT I2sOpusAudioPort::I2sSlot::Both

#define BOARD_AUDIO_INPUT_I2S_PORT 0
#define BOARD_AUDIO_INPUT_SAMPLE_RATE 24000
#define BOARD_AUDIO_INPUT_MCLK 46
#define BOARD_AUDIO_INPUT_BCLK 39
#define BOARD_AUDIO_INPUT_WS 2
#define BOARD_AUDIO_INPUT_DATA 40
#define BOARD_AUDIO_INPUT_DATA_BITS 16
#define BOARD_AUDIO_INPUT_VALID_BITS 16
#define BOARD_AUDIO_INPUT_SLOT_BITS 16
#define BOARD_AUDIO_INPUT_CHANNELS 2
#define BOARD_AUDIO_INPUT_SLOT I2sOpusAudioPort::I2sSlot::Both
#define BOARD_AUDIO_INPUT_RIGHT_SHIFT 0
#define BOARD_AUDIO_CAPTURE_CHANNEL I2sOpusAudioPort::CaptureChannel::Left
